name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'bugfix'
  - title: '🧰 Maintenance'
    labels:
      - 'chores'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '⚡ Performance'
    labels:
      - 'perf'
  - title: '🔧 Refactors'
    labels:
      - 'refactors'
  - title: '🧪 Tests'
    labels:
      - 'tests'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Docker Images

  ```bash
  docker pull ghcr.io/w6d-io/flask-auth-service:$RESOLVED_VERSION
  docker pull ghcr.io/w6d-io/flask-auth-service:latest
  ```

  ## Python Package

  ```bash
  pip install flask-auth-service==$RESOLVED_VERSION
  ```
